using System.Numerics;
using Content.Client.Parallax; // Frontier: Parallax control for the background
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Goobstation.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
//    private bool _draggin; // Commented by LuaM

// LuaM-start:
    /// <summary>
    /// If the branch is null, the user is on the branch selection screen.
    /// </summary>
    private ProtoId<TechDisciplinePrototype>? _selectedDiscipline;
// LuaM-end.

    /// <summary>
    /// Global position that all tech relates to.
	/// For dragging mostly
    /// </summary>
    private Vector2 _position = DefaultPosition;

    /// <summary>
	/// Captures the initial position to use with recenter button
    /// </summary>
//    private Vector2 _initialViewPosition; // Commented by LuaM

    /// <summary>
    /// Tracks if first initialization has happened
    /// </summary>
//    private bool _firstInitialization = true; // Commented by LuaM

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private const int GridSize = 64; // LuaM: 90 > 64

    /// <summary>
    /// Frontier: technology cards size.
    /// </summary>
    private const int CardSize = 64;

    /// <summary>
    /// Frontier: the distance between elements on the grid.
    /// </summary>
    private static readonly Vector2i DefaultPosition = Vector2i.Zero; //Frontier: 45,250 < 0,0

    private ParallaxControl _parallaxControl; // Frontier: Parallax control for the background

    private float _verticalScrollSpeed = 50; // Frontier: Allow mouse scroll

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Frontier: Initialize parallax background
//        _parallaxControl = new ParallaxControl // Commented by LuaM
        var disciplineParallax = new ParallaxControl // LuaM
        {
            ParallaxPrototype = "Default",
            HorizontalExpand = true,
            VerticalExpand = true,
        };
// LuaM-start:
        DisciplineSelectionScreen.AddChild(disciplineParallax);
        disciplineParallax.SetPositionInParent(0);
// LuaM-end.

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
// LuaM-start:
        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = "Default",
            HorizontalExpand = true,
            VerticalExpand = true,
        };
// LuaM-end.
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        // The drag container should be in the middle
        DragContainer.SetPositionInParent(1);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        // The recenter button should be at the top of the z-order (drawn last)
// Commented by LuaM
/*
        RecenterButton.SetPositionInParent(2);

        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();
*/
        BackToDisciplinesButton.OnPressed += _ => ShowDisciplineSelection(); // LuaM

        // Empty initialization
        UpdatePanels(List);
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
//        DragContainer.RemoveAllChildren(); // Commented by LuaM
        List = dict;
        BuildDisciplineGrid(); // LuaM

// Commented by LuaM
/*
        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);
            DragContainer.AddChild(control);

            // Set position for all tech, relating to _position
            var uiPosition = _position + proto.Position * GridSize;
            LayoutContainer.SetPosition(control, uiPosition);
            control.SelectAction += SelectTech;

            if (tech.Key == CurrentTech)
                SelectTech(proto, tech.Value);
        }
*/
// LuaM-start:
        if (_selectedDiscipline != null)
            PopulateResearchField();
// LuaM-end.
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            // i'm building the small-ass control here to spare me some mild annoyance in making a new file
            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

// Commented by LuaM
/*
    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        // Frontier: bound motion to a box
        var originalPosition = _position;
        _position += args.Relative;

        var diff = _position - originalPosition;
        // End Frontier: bound motion to a box

        // Move all tech
        foreach (var child in DragContainer.Children)
            {
            LayoutContainer.SetPosition(child, child.Position + diff); // Frontier: args.Relative<diff
        }
    }
*/

// LuaM-start:
    private void BuildDisciplineGrid()
    {
        DisciplineGrid.RemoveAllChildren();

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            var button = new Button
            {
                MinSize = new Vector2(240, 35),
                HorizontalExpand = false,
                Margin = new Thickness(8)
            };

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = true,
                Align = BoxContainer.AlignMode.Center
            };

            var texture = new TextureRect
            {
                Texture = _sprite.Frame0(discipline.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(8, 0, 8, 0)
            };
            container.AddChild(texture);

            var separator = new Label
            {
                Text = "|",
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 8, 0)
            };
            container.AddChild(separator);

            var progressLabel = new Label
            {
                Text = tier + "%",
                VerticalAlignment = VAlignment.Center,
                MinWidth = 50,
                Margin = new Thickness(0, 0, 8, 0)
            };
            container.AddChild(progressLabel);

            var nameLabel = new Label
            {
                Text = Loc.GetString(discipline.UiName),
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true
            };
            container.AddChild(nameLabel);

            button.AddChild(container);

            var capturedDisciplineId = disciplineId;
            button.OnPressed += _ => OnDisciplineSelected(capturedDisciplineId);

            DisciplineGrid.AddChild(button);
        }
    }
// LuaM-end.

// Commented by LuaM
    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
/*
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }
*/

// LuaM-start:
    private void OnDisciplineSelected(ProtoId<TechDisciplinePrototype> disciplineId)
    {
        _selectedDiscipline = disciplineId;
        DisciplineSelectionScreen.Visible = false;
        ResearchFieldScreen.Visible = true;
        PopulateResearchField();
    }
// LuaM-end.

// Commented by LuaM
    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
/*
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }
*/

// LuaM-start:
    private void ShowDisciplineSelection()
    {
        _selectedDiscipline = null;
        CurrentTech = null;
        DisciplineSelectionScreen.Visible = true;
        ResearchFieldScreen.Visible = false;
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        InfoContainer.AddChild(new Control
        {
            Margin = new Thickness(5),
            MinWidth = 450,
            VerticalExpand = true,
            HorizontalExpand = true
        });
// LuaM-end.
    }

// Commented by LuaM
/*
    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion
*/

// LuaM-start:
    private void PopulateResearchField()
    {
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
        InfoContainer.AddChild(new Control
        {
            Margin = new Thickness(5),
            MinWidth = 450,
            VerticalExpand = true,
            HorizontalExpand = true
        });

        if (_selectedDiscipline == null)
            return;

        _position = DefaultPosition;

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            if (proto.Discipline != _selectedDiscipline.Value)
                continue;

            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);
            DragContainer.AddChild(control);

            var uiPosition = _position + proto.Position * GridSize;
            LayoutContainer.SetPosition(control, uiPosition);
            control.SelectAction += SelectTech;

            if (tech.Key == CurrentTech)
                SelectTech(proto, tech.Value);
        }
    }
// LuaM-end.
    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        CurrentTech = proto.ID;
        var control = new FancyTechnologyInfoPanel(proto, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), availability, _sprite);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

// Commented by LuaM
/*
    /// <summary>
    /// Resets the view exactly to the initial position when the UI was first opened
    /// </summary>
    public void Recenter()
    {
        // Preserve the current tech items but reset the positions
        var diff = _initialViewPosition - _position;

        // First update the master position
        _position = _initialViewPosition;

        // Now update all child positions by the same delta
        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + diff);
        }
    }
*/

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
//	      _firstInitialization = true; // Commented by LuaM
        _selectedDiscipline = null;
        DisciplineSelectionScreen.Visible = true;
        ResearchFieldScreen.Visible = false;
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}